CREATE TABLE [dbo].[Education]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[SchoolName] VARCHAR(511) NOT NULL,
	[SchoolType] VARCHAR(255) NOT NULL,
	[SchoolURL] VARCHAR(1023) NOT NULL,
	[RewardType] VARCHAR(255) NOT NULL,
	[Major] VARCHAR(255) NULL,
	[GraduationDate] DATE NOT NULL,
	[GPA] DECIMAL(11,2) NOT NULL,
	[ImageId] UNIQUEIDENTIFIER NULL,

	CONSTRAINT FK_Education_Image FOREIGN KEY (ImageId) REFERENCES Image([Id])
)
