CREATE TABLE [dbo].[Link]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[LinkName] VARCHAR(255) NOT NULL,
	[LinkURL] VARCHAR(2047) NOT NULL,
	[LogoURL] VARCHAR(2047) NULL,
	[LogoAlt] VARCHAR(511) NULL,
	[OrderNumber] INT NULL
)
