CREATE TABLE [dbo].[Position]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[JobTitle] VARCHAR(255) NOT NULL,
	[CompanyName] VARCHAR(511) NOT NULL,
	[CompanyURL] VARCHAR(1023) NOT NULL,
	[Description] VARCHAR(MAX) NOT NULL,
	[StartDate] DATE NOT NULL,
	[EndDate] DATE NULL,
	[ImageId] UNIQUEIDENTIFIER NULL,

	CONSTRAINT FK_Position_Image FOREIGN KEY (ImageId) REFERENCES [Image]([Id])
)
