CREATE TABLE [dbo].[Project]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Name] VARCHAR(511) NOT NULL UNIQUE,
	[Description] VARCHAR(MAX) NOT NULL,
	[URL] VARCHAR(511) NULL,
	[RepoURL] VARCHAR(511) NULL
)
