CREATE TABLE [dbo].[Resume]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[FileName] VARCHAR(255) NOT NULL,
	[URL] VARCHAR(1023) NOT NULL,
	[Key] VARCHAR(255) NOT NULL,
	[CreationDate] DATE NOT NULL
)
