CREATE TABLE [dbo].[Tool]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(255) NOT NULL,
	[URL] VARCHAR(1023) NOT NULL,
	[Description] VARCHAR(MAX) NOT NULL,
	[CategoryId] INT NULL,
	[ImageId] UNIQUEIDENTIFIER NULL,

	CONSTRAINT FK_Tool_Category FOREIGN KEY (CategoryId) REFERENCES [Category](Id),
	CONSTRAINT FK_Tool_Image FOREIGN KEY (ImageId) REFERENCES [Image]([Id])
)
