CREATE TABLE [dbo].[User]
(
	[UserId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[UUID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	[Username] VARCHAR(255) NOT NULL,
	[Email] VARCHAR(255) NULL,
	[Password] VARBINARY(MAX) NULL,
	[PasswordSeed] VARBINARY(MAX) NULL
)
