CREATE TABLE [dbo].[User]
(
	[UserId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[UUID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	[Username] VARCHAR(255) NOT NULL,
	[Email] VARCHAR(255) NULL,
	[VerifiedEmail] BIT NOT NULL DEFAULT 0,
	[Password] VARBINARY(MAX) NULL,
	[PasswordSeed] VARBINARY(MAX) NULL,
	[RoleId] INT NULL,

	CONSTRAINT [FK_User_Role] FOREIGN KEY ([RoleId]) REFERENCES [Role]([RoleId])
)
