// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class BlacklistedToken
{
    public int TokenId { get; set; }

    public int UserId { get; set; }

    public string TokenType { get; set; }

    public string TokenData { get; set; }

    public virtual User User { get; set; }
}