// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class Link
{
    public int Id { get; set; }

    public string LinkName { get; set; }

    public string LinkUrl { get; set; }

    public string LogoUrl { get; set; }

    public string LogoAlt { get; set; }
}