// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models
{
    public partial class Project
    {
        public Project()
        {
            ProjectImages = new HashSet<ProjectImage>();
            ProjectTools = new HashSet<ProjectTool>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string RepoUrl { get; set; }

        public virtual ICollection<ProjectImage> ProjectImages { get; set; }
        public virtual ICollection<ProjectTool> ProjectTools { get; set; }
    }
}