// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class Resume
{
    public Guid Id { get; set; }

    public string FileName { get; set; }

    public string Url { get; set; }

    public string Key { get; set; }

    public DateTime CreationDate { get; set; }
}