// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class SpotifySongArtist
{
    public int Id { get; set; }

    public string SongId { get; set; }

    public string ArtistId { get; set; }

    public virtual SpotifyArtist Artist { get; set; }

    public virtual SpotifySong Song { get; set; }
}