// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class SpotifyTrackPlay
{
    public int Id { get; set; }

    public string SongId { get; set; }

    public int SessionId { get; set; }

    public int TimePlayed { get; set; }

    public virtual SpotifySession Session { get; set; }

    public virtual SpotifySong Song { get; set; }
}