// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models
{
    public partial class SpotifySession
    {
        public SpotifySession()
        {
            SpotifyTrackPlays = new HashSet<SpotifyTrackPlay>();
        }

        public int Id { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public int SongCount { get; set; }
        public int TimeListening { get; set; }
        public int? AccountId { get; set; }

        public virtual SpotifyAccount Account { get; set; }
        public virtual ICollection<SpotifyTrackPlay> SpotifyTrackPlays { get; set; }
    }
}