// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models
{
    public partial class SpotifyArtist
    {
        public SpotifyArtist()
        {
            SpotifyArtistAlbums = new HashSet<SpotifyArtistAlbum>();
            SpotifySongArtists = new HashSet<SpotifySongArtist>();
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }

        public virtual ICollection<SpotifyArtistAlbum> SpotifyArtistAlbums { get; set; }
        public virtual ICollection<SpotifySongArtist> SpotifySongArtists { get; set; }
    }
}